[build]
  base = "lab"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/editable"
  to = "/lab-seven-battery-editable.html"
  status = 200

[[redirects]]
  from = "/static"
  to = "/lab-seven-battery.html"
  status = 200

[[redirects]]
  from = "/macbook"
  to = "/macbook-air-replica.html"
  status = 200